name: Deploy WordlePixelArt to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to bagel-man.github.io/WordlePixelArt
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          external_repository: bageldeveloper/bagel-man.github.io
          publish_branch: main
          destination_dir: WordlePixelArt
          personal_token: ${{ secrets.GH_PAT }}
